# Generated by Django 5.1.3 on 2024-11-11 03:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_form', models.CharField(choices=[('01', 'Efectivo'), ('03', 'Transferencia Electrónica'), ('04', 'Tarjeta de Crédito'), ('28', 'Tarjeta de Débito')], max_length=20)),
                ('payment_method', models.CharField(choices=[('PUE', 'Pago en una sola exhibición'), ('PPD', 'Pago en parcialidades o diferido')], max_length=3)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_url', models.CharField(blank=True, max_length=500, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo restante después del pago', max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite de pago para pagos PPD', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
